 server {
        listen          80;
        server_name     reeflog.test.glijjy.com;
        access_log      /data/nginx/logs/reeflog.log;
        error_log       /data/nginx/logs/reeflog.log;

                location /
        {
                try_files $uri $uri/ /index.html;
                root /data/static/reeflog;
                index index.html;
                add_header Cache-Control "no-cache, no-store";
        }
        location ~ .*\.(htm|txt|html|js|css|png|jpg|ico|gif|eot|svg|ttf|woff|mp3|less|babel)$
        {
                root    /data/static/reeflog;
        }
}